---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Defaults for role gocd
#
GO_SERVER_SERVICE_NAME: "go-server"
GO_SERVER_USER: "go"
GO_SERVER_GROUP: "{{ GO_SERVER_USER }}"
GO_SERVER_VERSION: "16.1.0-2855"
GO_SERVER_HOME: "/var/lib/go-server"
GO_SERVER_CONF_HOME: "/etc/go"

# Java version settings
GO_SERVER_ORACLEJDK_VERSION: "7u80"
GO_SERVER_ORACLEJDK_BASE: "jdk1.7.0_80"
GO_SERVER_ORACLEJDK_BUILD: "b15"
GO_SERVER_ORACLEJDK_LINK: "/usr/lib/jvm/java-7-oracle"

# java tuning
GO_SERVER_JAVA_HOME: "{{ GO_SERVER_ORACLEJDK_LINK }}"

# Aptitude settings
GO_SERVER_APT_SOURCE: "deb http://dl.bintray.com/gocd/gocd-deb/ /"
GO_SERVER_APT_KEY_URL: "https://bintray.com/user/downloadSubjectPublicKey?username=gocd"
GO_SERVER_APT_NAME: "go-server"
GO_SERVER_APT_PKGS: ["apache2-utils"]

# gocd-oauth-login
GO_SERVER_OAUTH_LOGIN_VERSION: "1.2"
GO_SERVER_OAUTH_LOGIN_MD5: "31ad9ad1fe08452f73c56a44b035ee91"
GO_SERVER_OAUTH_LOGIN_JAR_URL: "https://github.com/gocd-contrib/gocd-oauth-login/releases/download/v{{ GO_SERVER_OAUTH_LOGIN_VERSION }}/github-oauth-login-{{ GO_SERVER_OAUTH_LOGIN_VERSION }}.jar"
GO_SERVER_OAUTH_LOGIN_JAR_DESTINATION: "{{ GO_SERVER_HOME }}/plugins/external/"

# go-server credentials
GO_SERVER_ADMIN_USERNAME: ""
GO_SERVER_ADMIN_PASSWORD: ""
GO_SERVER_BACKUP_USERNAME: ""
GO_SERVER_BACKUP_PASSWORD: ""

# go-server network settings
GO_SERVER_PORT: 8153
GO_SERVER_SECURE_PORT: 8154
GO_SERVER_FQDN: go-server.sandbox.edx.org

# H2 db settings
GO_SERVER_H2DB_PATH: "db/h2db"
GO_SERVER_H2DB_NAME: "cruise.h2.db"
GO_SERVER_H2DB_LOCATION: "{{ GO_SERVER_HOME }}/{{ GO_SERVER_H2DB_PATH }}/{{ GO_SERVER_H2DB_NAME}}"
GO_SERVER_H2DB_BACKUP_PATH: "artifacts/db_backup/"
GO_SERVER_H2DB_BACKUP_LOCATION: "{{ GO_SERVER_HOME }}/{{ GO_SERVER_H2DB_BACKUP_PATH }}/{{ GO_SERVER_H2DB_NAME }}"

# For use in backup/restore of a GoCD configuration.
GO_SERVER_BACKUP_FILENAME: "go-server-latest-backup.tgz"
GO_SERVER_TEMP_RESTORE_DIRECTORY: "/tmp/go-server-backup"
GO_SERVER_BACKUP_S3_BUCKET: "edx-tools-gocd-backup"
GO_SERVER_BACKUP_S3_OBJECT: "{{ GO_SERVER_BACKUP_FILENAME }}"
GO_SERVER_BACKUP_SNITCH_URL: "https://nosnch.in/4444444444"
GO_SERVER_BACKUP_APT_PKGS: ["python-pip", "jq"]
GO_SERVER_BACKUP_PIP_PKGS: ["boto", "awscli"]
GO_SERVER_BACKUP_API_URL: "http://localhost:8153/go/api/backups"
GO_SERVER_BACKUP_TMP_LOCATION: "/tmp/{{ GO_SERVER_BACKUP_FILENAME }}"
GO_SERVER_BACKUP_CRON_SCRIPT_LOCATION: "/root/gocd_backup.sh"

# password file setup
GO_SERVER_PASSWORD_FILE_NAME: "password.txt"
GO_SERVER_ADMIN_USERS: ["admin"]

# key for go-agents to autoregister with the go-server
GO_SERVER_AUTO_REGISTER_KEY: "dev-only-override-this-key"
